LATIR-2 Added Icon component
Jkierem/fundacion-latir pull request #41
Opened 2020-01-31 22:03 UTC by cavac96

Closes #2

2020-01-31 22:04 UTC, Jkierem requested changes

2020-01-31 22:04 UTC, Jkierem commented on src/components/Navbar/NarrowView/index.js
>          {/**This is where the icon will be*/}
Please remove this comment

2020-01-31 22:05 UTC, Jkierem requested changes
The branch seems to have conflicts with development. Do a rebase first

2020-02-01 02:25 UTC, cavac96 commented on src/components/Navbar/NarrowView/index.js
>          {/**This is where the icon will be*/}
Done

2020-02-01 02:26 UTC, cavac96 commented
Rebase done. @Jkierem

2020-02-01 12:06 UTC, Jkierem approved these changes
Awesome!😁

2020-02-01 12:06 UTC, merged